// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6iAncLaY6iM1zNVVy8-lTUNMJOBPJA3U',
    appId: '1:727270461549:web:d6b16ed95207692b5baf64',
    messagingSenderId: '727270461549',
    projectId: 'greenbite-4a69e',
    authDomain: 'greenbite-4a69e.firebaseapp.com',
    storageBucket: 'greenbite-4a69e.firebasestorage.app',
    measurementId: 'G-FZB7ZYTLEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdhiKhqrUJmPJ-LE5AEvELkc4-cAPzmwU',
    appId: '1:727270461549:android:f3fcef0d0c8dd74c5baf64',
    messagingSenderId: '727270461549',
    projectId: 'greenbite-4a69e',
    storageBucket: 'greenbite-4a69e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2NFNWME9pH85Bw7TUBJ0_h-tI5r4LYFI',
    appId: '1:727270461549:ios:ff8f244664f471085baf64',
    messagingSenderId: '727270461549',
    projectId: 'greenbite-4a69e',
    storageBucket: 'greenbite-4a69e.firebasestorage.app',
    iosClientId: '727270461549-f69pjbbqetbibib2cdvaeahukjfca3pb.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenBite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6iAncLaY6iM1zNVVy8-lTUNMJOBPJA3U',
    appId: '1:727270461549:web:e13fe149330ce9275baf64',
    messagingSenderId: '727270461549',
    projectId: 'greenbite-4a69e',
    authDomain: 'greenbite-4a69e.firebaseapp.com',
    storageBucket: 'greenbite-4a69e.firebasestorage.app',
    measurementId: 'G-BRBPP0M3WS',
  );
}